title: Karina Makhani
description: Personal site
url: https://karinamakhani.github.io
baseurl: ""                           
repository: karinamakhani/karinamakhani.github.io

author:
  name: Karina Makhani
  tagline: CS & Business @ Lehigh University, Software Engineer @ Amazon
  details: 
  avatar: /images/mecrop.jpeg 
  links:
    - label: LinkedIn
      url: https://www.linkedin.com/in/karinamakhani
    - label: GitHub
      url: https://github.com/karinamakhani

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project      
