title: Karina Makhani
description: Personal site
url: https://karinamakhani.github.io

author:
  name: Karina Makhani
  tagline: CS & Business @ Lehigh University, Software Engineer @ Amazon
  details: 
  #avatar: /assets/avatar.jpg 
  links:
    - label: LinkedIn
      url: https://www.linkedin.com/in/karinamakhani
    - label: GitHub
      url: https://github.com/karinamakhani

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
